#!/bin/sh

case "$1" in
	start)
		/sata/app/jellyfin/cmd/start.sh
		;;
	stop)
		/sata/app/jellyfin/cmd/stop.sh
		;;
	restart | reload)
		"$0" stop
		"$0" start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac
